2.0 get active model
graphgrid/graphgrid-sdk-python pull request #21
Opened 2022-05-03 20:23 UTC by NMPowell99

Allows the sdk to call the getActiveModel endpoint set up in [this PR](https://bitbucket.org/graphgrid/graphgrid-boot-nlp/pull-requests/228/20-getactivemodel)

2022-05-04 14:54 UTC, alexiudice requested changes
Left a comment for the class `GetActiveModelResponse`

2022-05-04 14:54 UTC, alexiudice commented on graphgrid_sdk/ggcore/sdk_messages.py
> +        self.task = generic_response.response
The fields of this model class don't line up with the returned java response `ModelMetrics`. That class has `modelName` and `trainedModelData` fields, but this only has `task`. 

Right now this loads the entire response into this `task` field as a string. I don't think this is correct. 

I think you want to match the `modelName` and `trainedModelData` fields from the java side, and then use a similar approach to our other response objects and extract the response string into a dict with `json.loads(generic_response.response)`. From there you can populate the `modelName` and `trainedModelData` fields.

2022-05-06 13:45 UTC, alexiudice requested changes
Need some changes on the `GetActiveModelResponse`, left two new comments.

2022-05-06 13:45 UTC, alexiudice commented on graphgrid_sdk/ggcore/sdk_messages.py
> +            self.logical_date = loaded.get('trainedModelData')
I'm confused why we're loading `modelName` into `dag_run_id` and `trainedModelData` into `logical_date`. 

Could we update these and the fields on the obj to match the java side?

2022-05-06 13:45 UTC, alexiudice commented on graphgrid_sdk/ggcore/sdk_messages.py
> +            self.model_name = loaded.get('modelName')
@NMPowell99  we're trying to keep the java and python responses aligned, could you change this to `self.modelName` and `self.trainedModelData` instead.

2022-05-06 13:45 UTC, alexiudice commented on graphgrid_sdk/ggcore/sdk_messages.py
> +    task: str
lets remove this unused `task` field and replace with `modelName: str` and `trainedModelData: dict`

2022-05-06 13:53 UTC, alexiudice approved these changes
Thanks for making those changes, looks good. Approving.

2022-05-06 18:12 UTC, HarryDunham approved these changes

2022-05-12 21:01 UTC, bradnussbaum approved these changes

2022-05-12 21:02 UTC, merged