2.0 nmt train pipeline
graphgrid/graphgrid-sdk-python pull request #24
Opened 2022-05-13 21:29 UTC by NMPowell99

Built on [trainedModelData class PR](https://github.com/graphgrid/graphgrid-sdk-python/pull/23)

Starts training for models provided in `models_to_train`, monitors training, and promotes models whose training was successful and accuracy is better than the current model (determined by `evaluate_models`, which is used in NMT as well), as long as `autopromote` is set to `True`.

There is a place where this will break until there is model task/type alignment (when get_active_model is called)

2022-05-13 21:40 UTC, NMPowell99 commented on graphgrid_sdk/ggcore/nmt_train_pipeline.py
> +                    selected_model = evaluate_models(self._nlp_client.get_active_model(models_to_train[i]), status)
get_active_model takes "task name" (e.g. named_entity_recognition), but right now we are giving it "model type" (e.g. "named-entity-recognition"). An error will be thrown here until there is alignment with model type/task

2022-05-16 16:43 UTC, alexiudice approved these changes
Looks good. I don't see anything that needs to change and the code makes sense to me. Approved!

2022-05-19 13:54 UTC, HarryDunham requested changes

2022-05-19 13:54 UTC, HarryDunham commented on graphgrid_sdk/ggcore/nmt_train_pipeline.py
> +                        completed_runs = completed_runs + 1
If one model finishes far quicker than all the other models won't that specific model's dagRun be counted multiple times as completed. Meaning you could have a scenario where only one (or any number < `num_models`) training job finishes but the outermost loop ends since you've looped `num_models` times and counted that singly completed model a `num_models` amount of times?

If so we need to remove any completed training call from the `nmt_status_responses` list.

@alexiudice @bradnussbaum

2022-05-19 15:31 UTC, alexiudice commented on graphgrid_sdk/ggcore/nmt_train_pipeline.py
> +                        completed_runs = completed_runs + 1
Linking thread https://atomrain.slack.com/archives/CGDK999QE/p1652968575012819

2022-05-20 15:05 UTC, HarryDunham approved these changes

2022-05-20 19:26 UTC, bradnussbaum approved these changes

2022-05-20 19:26 UTC, merged