2.0 datasetId
graphgrid/graphgrid-sdk-python pull request #28
Opened 2022-05-20 19:22 UTC by HarryDunham

* switch to `filename` as a field/param to specify
* Switch to NMT request body leveraging the datasetID rather than a dict
* Update SaveDatasetResponse for new fields

2022-05-20 23:19 UTC, bradnussbaum approved these changes

2022-05-20 23:27 UTC, bradnussbaum requested changes
We need to discuss this more.

2022-05-24 16:38 UTC, alexiudice approved these changes

2022-05-24 19:06 UTC, HarryDunham commented
I've updated this PR and rebased it on top of the latest 2.0. I've also added changes for the NMT training pipeline since that was leveraging `datasets` rather than `datasetId`

2022-05-25 16:15 UTC, bradnussbaum approved these changes

2022-05-25 16:15 UTC, merged